### ISSUE TITLE
NBT Data not working

### ISSUE THREAD

**Issue by TheMinecraftBrick** [ShaneBeeStudios/HungerGames#10]
**Is your feature request related to a problem? Please describe.**
Negative.

**Describe the solution you'd like**
This is a long shot in the dark but I figured I might as well ask. Looking to see if the dev could integrate quality armory (https://www.spigotmc.org/resources/quality-armory.47561/) support into the plugin such that plays can find items from QA in chests. This way you could create a more modern, battle royale, gun-based PVP hunger games along with the typical. It has been heavily requested on the server. The guns, weapons, and ammo should be able to spawn in chests during a match. If unable to add direct QA support, perhaps at least ItemBridge support could work since QA supports that? (https://www.spigotmc.org/resources/itembridge-save-items-and-use-them-wherever-you-want-including-other-plugins.77080/) Thanks!

**Describe alternatives you've considered**
We have attempted to do this on our own using NBT data of the guns, however, due to some issue (probably on QA's end, with how they detect weapons) the guns were unable to be fired

Thank you in advance!

**Comment by ShaneBeee** [comment]
Ok, so the data thing is a little bug, I missed converting color codes which is why items with Colors aren't working. 

I'll fix that in the next update.

**Comment by TheMinecraftBrick** [comment]
Thanks a lot man! 
Appreciate it!

**Comment by ShaneBeee** [comment]
Fixed in latest release
