### ISSUE TITLE
Allow all Hunger Games variable to be used for any game messages.

### ISSUE THREAD

**Issue by DamianJBurgos** [ShaneBeeStudios/HungerGames#11]
For example, I attempted to do "`player-joined-game: '&b&l<player> &7Has joined <arena>`" but it does not work because the variable "<arena> its not in the  "`# <arena> will be replaced with the name of the arena`" section.
<img width="1253" alt="Screen Shot 2020-05-11 at 10 47 07 PM" src="https://user-images.githubusercontent.com/16234394/81633693-5320c980-93db-11ea-8a76-d0ff2994afa8.png">
<img width="866" alt="Screen Shot 2020-05-11 at 10 48 35 PM" src="https://user-images.githubusercontent.com/16234394/81633696-5320c980-93db-11ea-9530-d4eb495ce4a7.png">

**Comment by ShaneBeee** [comment]
Ill be honest, its not feasible for me to go thru every single message and add the option for "<arena>" ... but I have gone ahead and added it to the player joined/left game messages
