### ISSUE TITLE
Players can drop items at the start of the game and change kits

### ISSUE THREAD

**Issue by Stixil** [ShaneBeeStudios/HungerGames#14]
Players at the beginning of the match during kit selection can drop items, pick another kit, or the same kit, and essentials duplicated infinite items this way at the start of a match. This is present on PaperMC 1.15.2, HG version 4.13.9. Thanks!

**Comment by ShaneBeee** [comment]
Have you tried removing plugins to see if maybe another plugin is overriding?

**Comment by Stixil** [comment]
I will check that, thanks!

**Comment by leviem1** [comment]
Verified issue does not exist in 4.13.12. I receive the "You cannot interact..." message.

**Comment by ShaneBeee** [comment]
> Verified issue does not exist in 4.13.12. I receive the "You cannot interact..." message.

Thank you for confirming that, as I too could not replicate this issue.
