### ISSUE TITLE
Spectator issues

### ISSUE THREAD

**Issue by Stixil** [ShaneBeeStudios/HungerGames#15]
Players in spectator mode will still experience hunger and can drop items, such as their compass. Also in the spectate players GUI, duplicate players often appear, I think it's when a player is eliminated, their head is replaced with another player who is still in the match. This is present on PaperMC 1.15.2, HG version 4.13.9. Thanks!

**Comment by ShaneBeee** [comment]
Ill look into this.

For future reference, please dont delete the issue template provided, but rather fill it out.
