### ISSUE TITLE
Arena Commands not working

### ISSUE THREAD

**Issue by ajpiano** [ShaneBeeStudios/HungerGames#20]
I am trying to set up some start/stop/join/death commands for my new experimentation with HungerGames on a server with some friends. However, no matter how I set them up, I cannot get the 'commands' section of the `arenas.yml` file to actually run when the events take place. Here is the relevant section of the file for one of the arenas. I apologise for filing what is more of a support issue on the bug tracker, but I don't really have much insight into how to audit why the commands are not firing as expected. The server is on Paper 1.15.2 and there are no other plugins besides HungerGames and bStats. 

```
 Forest-Park:
    bound:
      world: moshroomeess
      x: 2005
      y: 27
      z: -4503
      x2: 1120
      y2: 149
      z2: -3600
    info:
      cost: 0
      timer: 3600
      min-players: 1
      max-players: 16
    commands:
    - start: time set day <world>
    - stop: broadcast Game over man, game over
    - death: broadcast Sadly <player> has perished, yet we move
    - join: say Welcome <player> 
    spawns:
    - moshroomeess:1174:71:-3731:-56.394897:26.22268
    - moshroomeess:1182:63:-3932:-191.54604:14.22269
    - moshroomeess:1167:66:-4141:-192.14636:10.500013
    - moshroomeess:1169:64:-4387:-207.14615:10.199957
    - moshroomeess:1385:63:-4383:6.1537952:33.900055
    - moshroomeess:1382:76:-4182:91.20389:14.099992
    - moshroomeess:1382:66:-3978:-23.245943:22.649988
    - moshroomeess:1378:67:-3783:-293.24597:13.949976
    - moshroomeess:1541:63:-3792:-248.246:29.700024
    - moshroomeess:1544:63:-4014:-272.99634:20.54998
    - moshroomeess:1545:75:-4223:-334.64633:14.399957
    - moshroomeess:1537:68:-4435:-222.4464:5.8499537
    - moshroomeess:1703:77:-4441:-341.39615:30.149942
    - moshroomeess:1700:69:-4241:-271.79617:23.849945
    - moshroomeess:1700:63:-4038:-2.6962585:9.899939
    - moshroomeess:1704:81:-3835:-33.44519:28.64992
    lobbysign: moshroomeess:1505:172:-4020
    border:
      center: moshroomeess:1504:170:-4020
```

Any insight you can provide into how to figure out what's going on here or indicate what I'm doing wrong would be immensely appreciated. Thanks!

**Comment by ShaneBeee** [comment]
I will need to look into this. Are the commands attempting to run in your console?

**Comment by ShaneBeee** [comment]
Closing due to lack of response.
