### ISSUE TITLE
Option to set Item Frames as breakable in game

### ISSUE THREAD

**Issue by Griefo** [ShaneBeeStudios/HungerGames#22]
**Is your feature request related to a problem? Please describe:**
I'd like to have specific obtainable items as a reward for accessing areas of my hunger games map that are hidden or hard to reach, but item frames cannot be broken in game, even when they are set as a breakable block in the config.

**Describe the solution you'd like:**
Because some people like that item frames can't be destroyed, for decorative purposes, I propose a toggleable option in the config that sets item frames and breakable or not breakable.

**Describe alternatives you've considered:**
There aren't really any other alternatives apart from something like a furnace containing the item, but something like that wouldn't be as obvious as an item frame, would be physically more limited, and accessing a furnace to remove an item wouldn't be as fast as just breaking an item frame.
**Additional context:**
I don't think there would be any gripes with having this toggleable option, and either way we're getting indestructible and invisible tags for item frames in the next update, as you already know

**Comment by ShaneBeee** [comment]
Are you wanting item frames to be broken? OR are you wanting to allow players to remove items?

And are you wanting this rolled back as well when the game is over?

**Comment by ShaneBeee** [comment]
Ok, well I didn't hear back so I took a slightly different route.
Players won't be able to break item frames, but they will be able to remove items from the frames. 
This is configurable of course.

Personally I see no need for the player to break the frame itself.

The removed item will also be logged and rolled back.
