### ISSUE TITLE
[BUG] teleport on arena join teleports to the wrong coords

### ISSUE THREAD

**Issue by frytkisasmaczne** [ShaneBeeStudios/HungerGames#27]
**Describe the bug**
when joining arena, player gets teleported somewhere near the spawnpoint, only sometimes landing on the right block. Generally the player gets teleported to from 0 to 2 coordinates less in any axis (y too sometimes, landing inside the ground) from the correct spawnpoint.

**To Reproduce**
create arena, set spawns, lobby wall and join, either using sign or command doesn't matter

**Expected behavior**
player gets teleported to the block where the spawnpoint was set

**Screenshots/Errors**
on console/logs the join is clean, no errors/warns

**Version Info:**
 - **Plugin Version:**  v4.13.11
 - **Server Version/Platform** PaperSpigot 1.15.2 build 348
I'm running itzg/minecraft-server in docker, not that I think it makes much of a difference

**Additional context**
first encountered on my server with all the basic known plugins like essentials, FAWorldEdit, multiverse-core/inventories, so I started another container to isolate the plugin and got the same bug

**Comment by ShaneBeee** [comment]
Please check for updates and update before reporting issues.

This issue has already been fixed.
<img width="852" alt="Screen Shot 2020-06-15 at 1 08 05 PM" src="https://user-images.githubusercontent.com/20008482/84701156-4bd46a80-af09-11ea-980e-e2df8f8d56b4.png">
