### ISSUE TITLE
[BUG] Mis-matched inventories when spectating

### ISSUE THREAD

**Issue by elsell** [ShaneBeeStudios/HungerGames#30]
**Describe the bug**
When a player is playing with more than 2 people and gets killed, they enter spectator mode. At this point, sometimes they receive the spectator compass, and other times they receive an empty inventory. 

Upon leaving the match or the match ending, they are teleported back to the HungerGames lobby. **Their inventory is not what it was when they joined.** 

It's unclear exactly where the items come from, but it seems to be mixed up with inventories they've held in other worlds. 

**To Reproduce**
1) Join a match with more than 2 players, and an item in your inventory
2) Join spectator mode by being killed
3) Notice the *potentially* incorrect inventory
4) Upon match-end, take note of incorrect inventory at the lobby

_Alternatively:_
1) Have a match started, either by players joining, or `/hg forcestart <arena>`
2) Spectate the arena by using `/hg spectate <arena>`
3) Notice the *potentially* incorrect inventory
4) Upon match-end, take note of incorrect inventory at the lobby

**Expected behavior**
1) In-game spectators should be given the compass and nothing else upon being killed and joining spectators
2) Players, upon the match ending, should teleport back to the lobby and be given back the items that they joined with.

**Screenshots/Errors**
No console errors are present. 
![image](https://user-images.githubusercontent.com/35787503/85816960-a86e2b80-b73a-11ea-8669-a4f6af9aa839.png)
_Image showing a player in spectator mode (after running `/hg spectate <arena>`) with an inventory that contains items that were 'lost' last time they spectated. The items in the inventory are those that were originally in their inventory before joining a game. They're now 'stuck' in the HungerGames world.)_

**Version Info:**
 - **Plugin Version:** 4.13.12
 - **Server Version/Platform** Paper 1.15.2

**Additional context**
I'm using two plugins that also affect inventories: Multiverse-Inventories and Restricted Creative. 

**This bug seems to only affect players placed in spectator mode. Players that join and leave without spectating seem to be unaffected.**

**Plugin List:**
```
ActionHealth*, AdvancedBan*, AdvancedNMotd*, AdvancedPortals, AltFinder, AsyncWorldEdit, AuthMe, AutoMessager, BetterRTP, BiomeFinder*, BlocksHub, BountifulAPI, BountyHunters, Citizens, ClearLag, CoreProtect, CrazyCrates, CrazyEnchantments, DeluxeHub, DeluxeMentions*, DiscordSRV, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, eZProtector, Factions, FastLeafDecay, Graves, HolographicDisplays, HungerGames, Images, IridiumSkyblock, JoinEventsPro, JumpPads, KeepChunks, LibsDisguises, LuckPerms, MassiveCore, mcMMO, MobArena, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, Paintball, Parkour, PlaceholderAPI, PlayerHeads, Playtimes*, PlotSquared, ProtocolLib, pvparena, PvPManager, Racing, RemoveWanders, RestrictedCreative, SignShopHelper, SimpleRename, StayPut*, TAB, UltraCosmetics, UsefulWanderingTrader, Vault, ViewDistanceTweaks, VoidSpawn, Votifier, WorldCommand*, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags
```

**Comment by ShaneBeee** [comment]
Ok, I THINK I have fixed this. 
Im going to do more testing and make sure it properly works.

**Comment by ShaneBeee** [comment]
Ok, an update has been posted on [**Spigot**](https://www.spigotmc.org/resources/hungergames.65942/update?update=343890) which I believe fixes this issue.
