### ISSUE TITLE
[BUG] Can move whilst in Arena Lobby

### ISSUE THREAD

**Issue by TreemanKing** [ShaneBeeStudios/HungerGames#31]
**Describe the bug**
While holding sprint and space bar, one can move blocks on the same y axis or lower.

**To Reproduce**
Hold sprint, w and repetitively use space bar.

**Expected behavior**
You should be able to move forward
**Screenshots/Errors**
[https://imgur.com/a/b9s2y6L](url)

**Version Info:**
 - **Plugin Version:** <Recent Version(4.13.12>
 - **Server Version/Platform** <Spigot 1.15.2>

**Comment by ShaneBeee** [comment]
When this happens, is the player's food level at 1 or higher?
This is a known issue, with other plugins overriding the players hunger, which in turn allows the player to Spring.

**Comment by TreemanKing** [comment]
Yes, the hunger is higher, we thought it was a feature of the plugin as I am only running Hunger Games, and terraforming mods such as WorldEdit and VoxelSniper and EssentialsX. I will do a test run later without Essentials to see if this is fixed.

**Comment by TreemanKing** [comment]
I've tested it, and you were correct. Thanks a lot :) Looking forward for the 1.6 update :+1:
