### ISSUE TITLE
[BUG] Can't change messages from language.yml

### ISSUE THREAD

**Issue by ZhenjaMax** [ShaneBeeStudios/HungerGames#39]
**Describe the bug**
Can't change message for plugin. Changes in language.yml doesn't affect on plugin.

**To Reproduce**
1. Change one of messages in language.yml.

**Expected behavior**
Changed message in chat.

**Version Info:**
 - **Plugin Version:** 4.13.16
 - **Server Version/Platform** Paper 1.16.1 (build #131)

**Additional context**
Pinned my language.yml (txt because of unsupported format)
[language.txt](https://github.com/ShaneBeeStudios/HungerGames/files/5053417/language.txt)
and screenshot in game.
![unknown](https://user-images.githubusercontent.com/54914800/89831732-ff9f5280-db66-11ea-97f9-c07d8675040b.png)

**Comment by ShaneBeee** [comment]
Which message exactly did you change?
