### ISSUE TITLE
[BUG] Spectator mode and GAMEMODE ADVENTURE

### ISSUE THREAD

**Issue by Volgeop** [ShaneBeeStudios/HungerGames#42]
**Describe the bug**

Hi, when I have set gamemode adventure in server.properties, but when set normal gamemode survival via multiverse in arena world, then still players CAN'T FLY in "spectator" mode, after they'll die.

**To Reproduce**

Enable gamemode adventure in server.properties (due to protection of lobby etc., don't wanna external plugin for it), and then enable gamemode survival via multiverse worlds.yml in the specific world, where's set hungergames arena.

Then die, and you'll be in spectator mode. (try it without admin perms), and then you couldn't fly.

**Expected behavior**

I expect, that when there's gamemode survival via multiverse set, then players should be able to fly. Either, when they're in gamemode adventure, I think it still should overwrite somehow to allow them fly.

**Version Info:**
 - **Plugin Version:**  4.13.17
 - **Server Version/Platform**  Paper 1.16.2

**Comment by ShaneBeee** [comment]
Looking thru the code, I cant find anything that would prevent the player from flying, other than a config setting.
Are you sure you have spectate.fly enabled in your config?

**Comment by Volgeop** [comment]
Yeah it was, did you tried it with gamemode adventure like I wrote in steps to reproduce?

**Comment by ShaneBeee** [comment]
No, I haven't tried anything yet. I was just asking a question.

I think I may have found the issue. It appears the game mode is set before the spectator is TPd to the arena, so that could be the issue.

**Comment by ShaneBeee** [comment]
Ok I tested a bunch of times. I was not able to replicate the issue.
Im thinking something on your server is overriding the flight. Im not sure.
I will try do some things to work around that, but as it stands, I can not replicate the issue.

**Comment by ShaneBeee** [comment]
If you would like, try [**this build**](https://github.com/ShaneBeeStudios/HungerGames/suites/1119149759/artifacts/15828263) Im not sure if it fixes the issue you are having but hopefully it does.

**Comment by Volgeop** [comment]
Yeah, works! Great.
