### ISSUE TITLE
[BUG] SetLobbyWall Command Doesnt work

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [ShaneBeeStudios/HungerGames#43]
**Describe the bug**
Internal error occurs when I type /lobbysigns (arena) when looking at 1/3 signs

**To Reproduce**
type /hg setlobbywall (arena)

**Expected behavior**
The arena to be joinable by a sign

**Screenshots/Errors**
Error Message: https://mcpaste.io/29c5c74a47e5c5b3

**Version Info:**
 - **Plugin Version:** 4.1.3
 - **Server Version/Platform** BungeeCord 1.8 - 1.16

**Additional context**

**Comment by ShaneBeee** [comment]
The plugin only supports 1.13.2+

<img width="1005" alt="Screen Shot 2020-08-30 at 11 00 21 PM" src="https://user-images.githubusercontent.com/20008482/91687473-a480d000-eb14-11ea-8e62-142eb204200c.png">

**Comment by MinecraftMan1013number2** [comment]
My server version is paper 1.13.2 with bungeecord attached

**Comment by ShaneBeee** [comment]
Doesn't look like it is:

<img width="1576" alt="Screen Shot 2020-08-30 at 11 03 18 PM" src="https://user-images.githubusercontent.com/20008482/91687620-0e00de80-eb15-11ea-8e70-8e384a5364a9.png">
