### ISSUE TITLE
[BUG] The "free-roam" message remains within 10 seconds.

### ISSUE THREAD

**Issue by UnknownName404** [ShaneBeeStudios/HungerGames#44]
**Describe the bug**

I took 15 seconds instead of 10 seconds by default ( config ), but the message does not change in game.

**Version Info:**
 - **Plugin Version:** 4.13.17
 - **Server Version/Platform** 1.16.2 - paper 157

**Comment by ShaneBeee** [comment]
Turns out this was a bug I already fixed at some point. This will be seen in the next update.
