### ISSUE TITLE
[BUG] latest dev version write multiple all messages

### ISSUE THREAD

**Issue by andris155** [ShaneBeeStudios/HungerGames#53]
**Describe the bug**

Latest dev version write multiple all plugin messages.

**To Reproduce**

Compile the latest dev version and use on the server.

**Expected behavior**

Write all messages only once.

**Screenshots/Errors**

![97781819-28474f00-1b8e-11eb-8bd7-45ce842ba8a7](https://user-images.githubusercontent.com/8324198/97783656-8c234500-1b99-11eb-845d-74ac810acc6d.png)
![97781816-22ea0480-1b8e-11eb-8198-9c47a6035859](https://user-images.githubusercontent.com/8324198/97783658-8e859f00-1b99-11eb-815e-cd2ef5bf67ae.png)
![97781822-2c736c80-1b8e-11eb-91fd-0accce78d2b7](https://user-images.githubusercontent.com/8324198/97783664-93e2e980-1b99-11eb-807e-c1219e97d6b1.png)

**Version Info:**
 - **Plugin Version:** 4.14.0
 - **Server Version/Platform** Paper 1.16.3

**Additional context**

**Comment by ShaneBeee** [comment]
Thanks for letting me know, I will look into it.

**Comment by ShaneBeee** [comment]
Ok I had 2 players on the server, and I had both of us join the game:

<img width="1667" alt="Screen Shot 2020-11-07 at 8 23 12 PM" src="https://user-images.githubusercontent.com/20008482/98456955-5a7d2180-2137-11eb-84dc-d8dc9ee988d5.png">

Could not find any issues there.

Tried again having 1 player join, and force starting it:
<img width="1667" alt="Screen Shot 2020-11-07 at 8 24 11 PM" src="https://user-images.githubusercontent.com/20008482/98456960-649f2000-2137-11eb-8ca9-cb476a1a42ce.png">

Same thing, no issues there.

Needless to say, I can not replicate any issues.
