### ISSUE TITLE
Option to edit the message interval for the "The game is ending in <minutes> minute(s), and <seconds> second(s)!" message

### ISSUE THREAD

**Issue by TheMelonensaft** [ShaneBeeStudios/HungerGames#55]
I just started using ShaneBee's Hunger Games Plugin and one of the first things i noticed while testing was the The game is ending in... message that gets send every 30 seconds. I think this is kinda annoying and would like an option to configure the interval time or disable it.

It would be nice to have a solution where you get the message for example at minute 20, minute 10, minute 5, minute 2:30, minute 1, 30 sec, 15, sec and then 10...9...8.. you get my point. If this is to complicated (I dont know anything about this sort of stuff) as a alternative it would be nice to be able to set the interval or turn it off completely.

Sorry for my bad english, english isn't my main language so sometimes i have difficulty putting my thoughts into words.

**Comment by ShaneBeee** [comment]
Ok, so based on how the timer works in the game (it runs every 30 seconds and handles a few things for the game), it's not really feasible for me to rewrite the entire timer to allow for setting the timers for messages.

That said, I set it up so if the messages are not set in the lang file, they won't be sent, ex:
```yaml
game-ending-minsec: ''
game-ending-min: ''
game-ending-sec: ''
```

This will appear in the next update
