### ISSUE TITLE
Players can walk forwards when they join

### ISSUE THREAD

**Issue by HexTheLynx** [ShaneBeeStudios/HungerGames#56]
hi im running the current latest version of hunger games and theres a major glitch where players can move for about 3 seconds when they first join an arena, if you can fix this asap that would be great!

**Comment by ShaneBeee** [comment]
what difficulty is your world set on?
If peaceful, change it to something other than peaceful.

**Comment by HexTheLynx** [comment]
> what difficulty is your world set on?
> If peaceful, change it to something other than peaceful.

they were all on normal so i changed them to easy but they can still walk forwards when they join.

**Comment by ShaneBeee** [comment]
Is the player's hunger bar going up?
HG sets it to 1 ... yet I know some plugins bring it up for whatever reason. Sounds like a conflicting plugin issue.

**Comment by HexTheLynx** [comment]
no it is at 1 hunger but there are no other plugins that i would think conflict between them cuz hunger games is my only plugin that i use for regular players the rest is just admin stuff

**Comment by ShaneBeee** [comment]
Hmm... that is odd. Ill have to do some testing and see if I can replicate this.

**Comment by HexTheLynx** [comment]
Here is evidence https://youtu.be/n8TxDGiX6Q0 it happens to every player no matter what permission

**Comment by ShaneBeee** [comment]
Ok, so a couple things
1) I couldn't replicate this. Im not saying it doesn't happen as your video sure as heck shows it does, I just can't replicate it.
2) Looking thru the code, the only conclusion I can come to is a possible big of lag when the arena is loading. 
Long story short the player is TPing to the arena, which is forcing chunks to load, which in turn is pausing HungerGames trying to do its thing.
I have tried to re-order some things, hoping that the chunks will load before the player TPs in ... thus cutting out the lag for setting the food level.
Please give this build a try and let me know if it fixes the issue:
https://github.com/ShaneBeeStudios/HungerGames/suites/1475836174/artifacts/25449329

**Comment by HexTheLynx** [comment]
The link doesnt work.

**Comment by ShaneBeee** [comment]
oyy GitHub drives me nuts sometimes 

try this link:
https://github.com/ShaneBeeStudios/HungerGames/actions/runs/363833599

And click on the artifact

**Comment by HexTheLynx** [comment]
Thanks it works now
