### ISSUE TITLE
cant use hg commands anymore (BUG)

### ISSUE THREAD

**Issue by JackFradley** [ShaneBeeStudios/HungerGames#63]
so ive been using this plugin for only a day now and this could very well be an already fixed issue. the hg command had been working for multiple hours and we even got some games in, but after something happened (i dont know what) every time i use the hg command the only prompt after it is my username. i havent gotten to testing if this happens with other players but even if i type out the whole comand on my own it doesnt work. any ideas?

**Comment by JackFradley** [comment]
so i have somewhat solved the issue. i had to delete all of the config files and reset them though.

**Comment by JackFradley** [comment]
Progress!! i was able to recreate the problem. it happened somewhere in my items or config file. it might be one of my special items i tried to add.

**Comment by JackFradley** [comment]
i found the problem. kind of a rookie mistake i think.i accidentally set some of the values for items chances to spawn as x:0.5 but that didnt work. is there anyway i can set a value to lower than 1?

**Comment by ShaneBeee** [comment]
> is there anyway i can set a value to lower than 1?

no, the number is an integer.
