### ISSUE TITLE
Hologram leaderboard isn't working [BUG]

### ISSUE THREAD

**Issue by Greyhound10** [ShaneBeeStudios/HungerGames#65]
**Describe the bug**
When I type /hd addline [name] &b%hungergames_lb_deaths_p_1% &7: &a%hungergames_lb_deaths_s_1% it just shows exactly what I put. Not any values, just %hungergames_lb_deaths% etc. 

**To Reproduce**
Create a hologram. do /hd addline &b%hungergames_lb_deaths_p_1% &7: &a%hungergames_lb_deaths_s_1%.

**Expected behavior**
I thought it would come up with a name on the left side and the amount of deaths on the right.

**Screenshots/Errors**

**Version Info:**
 - **Plugin Version:** Latest plugin version. I'm on 1.16.4 java.
 - **Server Version/Platform** 1.16.4 Spigot

**Additional context**

**Comment by ShaneBeee** [comment]
> Create a hologram. 

with what? HungerGames has nothing to create holograms

> Latest plugin version. 

this is not a plugin version

**Comment by ShaneBeee** [comment]
Closing due to no response
