### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BlitzGamez** [ShaneBeeStudios/HungerGames#68]
**Describe the bug**
Players are able to break blocks at the edge of the border.

**To Reproduce**
Simply walk up to incoming border, attempt to break blocks. (Not sure if it's server sided bug, but players cannot break blocks when they're not near the border.)

**Expected behavior**
I expected players to not be able to break blocks. These specific broken blocks do not rollback when the game is over.

**Version Info:**
 - **Plugin Version:** 4.15.1
 - **Server Version/Platform** Spigot 1.16.4

**Additional context**
This has only happened at the border, no other blocks seem breakable and everything else functions as normal. Border is overall funky imo; Border option is set to true but when set to start at a specific time, border is already closing in.

**Comment by BlitzGamez** [comment]
Never mind, it was a permission issue on my end.

**Comment by ShaneBeee** [comment]
1) Glad you figured it out

2) Sorry, I was going to reply, and I got sidetracked by like 16 other things
