### ISSUE TITLE
[BUG] /hg spectate not working.

### ISSUE THREAD

**Issue by quinnconnolly03** [ShaneBeeStudios/HungerGames#7]
**Describe the bug**
/hg spectate does not exist. It does not give any option to spectate just a list of the other commands.

**To Reproduce**
Type in /hg spectate <arena> in chat and it will just give you the other available commands.

**Version Info:**
 - **Plugin Version:** 14.13.9
 - **Server Version/Platform** Spigot 1.15.2

**Comment by ShaneBeee** [comment]
do you have spectate enabled in the config?

**Comment by quinnconnolly03** [comment]
I am that stupid, it worked, my bad.
