### ISSUE TITLE
Question about permissions in arenas.

### ISSUE THREAD

**Issue by kmsungporant** [ShaneBeeStudios/HungerGames#72]
Hi, 

I was wondering if there was a way to enable outside plugin command usage. 
Every time players try to do a command outside of the plugin, it says "You can not use non-HungerGames commands while in-game!"

I've been trying to figure out a way to disable it but I'm completely stuck. 

Thanks.

**Comment by ShaneBeee** [comment]
<img width="1174" alt="Screen Shot 2020-12-04 at 8 55 41 PM" src="https://user-images.githubusercontent.com/20008482/101234326-1c5e1980-3673-11eb-86d2-5b37d4083eda.png">

**Comment by ShaneBeee** [comment]
Closing due to no further response
