### ISSUE TITLE
[BUG] Border not centered

### ISSUE THREAD

**Issue by qwertydesk** [ShaneBeeStudios/HungerGames#8]
**Describe the bug**
When using the plugin (HungerGames 4.13.9) on a 1.15.2 Spigot server, setting the border-center does not actually cause the border to be centered at the coordinates, but rather centers them around the first spawn added to the arena. From testing with some of the other border-based commands, it seems that all of them work as intended except for the center.

**To Reproduce**
Using Multiverse and the HG plugin in conjunction. Border center was set by commands in game. 

Arena.yml was configured as follows, using in game commands:
[`Pastebin link`](https://pastebin.com/m94RsewB)

**Expected behavior**
I would hope that the border would be centered at the border center.

**Screenshots/Errors**
![weirdborder](https://user-images.githubusercontent.com/64885510/81141259-16b42000-8f3a-11ea-822e-6b395ddf69c6.png)

**Version Info:**
 - **Plugin Version:** 4.13.9 (From Spigot)
 - **Server Version/Platform:** Spigot 1.15.2

**Comment by ShaneBeee** [comment]
Hmm, interesting, thanks for letting me know.
I will look into it.

**Comment by HaddenBat** [comment]
I have the same issue

**Comment by quinnconnolly03** [comment]
I am not sure which version you are using but in version 4.13.9 in the **config.yml** under the **border** section there is an option to _center-on-first-spawn_ set that too **false** and now when you play a match of Hunger Games it centers the border on the point of your liking.
If none of that made sense let me know!
